kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgsql-pv
  labels:
    app: pgsql 
spec:
  storageClassName: pgsql-storageclass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgsql-pvc
  labels:
    app: pgsql
spec:
  storageClassName: pgsql-storageclass 
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
