apiVersion: v1
kind: Service
metadata:
  name: pgsql 
  labels:
    app: pgsql 
spec:
  ports:
  - port: 5432
    name: pgsql
  clusterIP: None
  selector:
    app: pgsql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql-statefulset
  labels:
    app: pgsql
spec:
  serviceName: "pgsql"
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: vfrancax1/postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pgsql-db-creds
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql-db-creds
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pgsql-db-creds
                key: database
        ports:
        - containerPort: 5432
          name: pgsqldb
        volumeMounts:
        - name: pgsql-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgsql-pv
        persistentVolumeClaim:
          claimName: pgsql-pvc
